#FROM ubuntu:20.04
FROM uhd:latest


ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get -y upgrade
RUN apt-get install -y libfftw3-dev \
	libmbedtls-dev \
	libsctp-dev \
	libconfig++-dev \
	net-tools \
	nano \
	libtool pkg-config build-essential autoconf \
	automake \
	git  \
	python3 python3-distutils python3-pip python3-apt \
	libzmq3-dev python3-zmq \
	software-properties-common

RUN apt-get update 
RUN add-apt-repository ppa:gnuradio/gnuradio-releases
RUN apt-get update
RUN apt-get install -y gnuradio xterm python3-gi \
	gobject-introspection gir1.2-gtk-3.0 \
	iputils-ping \
	iproute2 libx11-dev iperf

RUN pip3 install --upgrade pip
RUN pip3 install gym pandas torchvision tensorboard redis

	 
RUN apt-get update 
RUN apt-get install -y cmake 
RUN cmake --version
	


## copy srsran and Pytorch
RUN mkdir -p home/afc/git/4G_EdgeRIC_uhd
WORKDIR "/home/afc/git/4G_EdgeRIC_uhd"
COPY . .

## compile srsRAN project
WORKDIR "/home/afc/git/4G_EdgeRIC_uhd/srsran"
RUN cp zmq.h /usr/local/include
RUN cp zmq.hpp /usr/local/include

##RUN rm -r build
RUN mkdir build
WORKDIR "/home/afc/git/4G_EdgeRIC_uhd/srsran/build"
RUN cmake ..
RUN make 
RUN make install
RUN ./srsran_install_configs.sh user







