FROM edgeric_base_oaic:latest

#Copy Code (Cur Dir to Container)
WORKDIR "/home/EdgeRIC-A-real-time-RIC"
# COPY . .

#WORKDIR "/home/EdgeRIC-A-real-time-RIC/srsran-enb/build"
#RUN make -j 10

# WORKDIR "/home/EdgeRIC-A-real-time-RIC/srsran-enb"
# RUN rm -rf build
# RUN mkdir build
# WORKDIR "/home/EdgeRIC-A-real-time-RIC/srsran-enb/build"
# RUN cmake ../
# RUN make -j $(nproc)
# # RUN ./srsran_install_configs.sh user


# ## Compile srsran for ue
# WORKDIR "/home/EdgeRIC-A-real-time-RIC/srsran-ue"
# RUN rm -rf build
# RUN mkdir build
# WORKDIR "/home/EdgeRIC-A-real-time-RIC/srsran-ue/build"
# RUN cmake ../
# RUN make -j $(nproc)

# WORKDIR "/home/EdgeRIC-A-real-time-RIC"
# RUN ip netns add ue1
# RUN ip netns add ue2






