# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: control_actions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='control_actions.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x63ontrol_actions.proto\"7\n\x11SchedulingWeights\x12\x11\n\tran_index\x18\x01 \x01(\r\x12\x0f\n\x07weights\x18\x02 \x03(\x02\"3\n\x08\x42lanking\x12\x11\n\tran_index\x18\x01 \x01(\r\x12\t\n\x01\x61\x18\x02 \x01(\x05\x12\t\n\x01\x62\x18\x03 \x01(\x05\x62\x06proto3')
)




_SCHEDULINGWEIGHTS = _descriptor.Descriptor(
  name='SchedulingWeights',
  full_name='SchedulingWeights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ran_index', full_name='SchedulingWeights.ran_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weights', full_name='SchedulingWeights.weights', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=80,
)


_BLANKING = _descriptor.Descriptor(
  name='Blanking',
  full_name='Blanking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ran_index', full_name='Blanking.ran_index', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='a', full_name='Blanking.a', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='Blanking.b', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=133,
)

DESCRIPTOR.message_types_by_name['SchedulingWeights'] = _SCHEDULINGWEIGHTS
DESCRIPTOR.message_types_by_name['Blanking'] = _BLANKING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SchedulingWeights = _reflection.GeneratedProtocolMessageType('SchedulingWeights', (_message.Message,), dict(
  DESCRIPTOR = _SCHEDULINGWEIGHTS,
  __module__ = 'control_actions_pb2'
  # @@protoc_insertion_point(class_scope:SchedulingWeights)
  ))
_sym_db.RegisterMessage(SchedulingWeights)

Blanking = _reflection.GeneratedProtocolMessageType('Blanking', (_message.Message,), dict(
  DESCRIPTOR = _BLANKING,
  __module__ = 'control_actions_pb2'
  # @@protoc_insertion_point(class_scope:Blanking)
  ))
_sym_db.RegisterMessage(Blanking)


# @@protoc_insertion_point(module_scope)
